
package studinfomgmtsys;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * The purpose of this class is to provide the user the ability to enter student grade averages to database
 * @author Ralph Julsaint
 */
public class AddGradesWindow extends javax.swing.JFrame {
    //instance variables
    private final String URL = "jdbc:derby://localhost:1527/schoolDB;create=false";
    private final String username = "julsaint";
    private final String password = "julsaint";
    private final String submitGrades = "INSERT INTO grades (studentID, readingAverage, mathAverage, scienceAverage, socialStudiesAverage) VALUES (?, ?, ?, ?, ?)";
    private PreparedStatement submitGradesStatement;
    /**
     * Creates new form AddGradesWindow
     */
    public AddGradesWindow() {
        super("Add Grades");
        initComponents();
        setFrame();
        setComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentLabel = new javax.swing.JLabel();
        readingAverageLabel = new javax.swing.JLabel();
        mathAverageLabel = new javax.swing.JLabel();
        scienceAverageLabel = new javax.swing.JLabel();
        socialStudiesAverageLabel = new javax.swing.JLabel();
        readingAverageTextField = new javax.swing.JTextField();
        mathAverageTextField = new javax.swing.JTextField();
        studentComboBox = new javax.swing.JComboBox<>();
        scienceAverageTextField = new javax.swing.JTextField();
        socialStudiesAverageTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studentLabel.setText("Student:");

        readingAverageLabel.setText("Reading Average:");

        mathAverageLabel.setText("Math Average:");

        scienceAverageLabel.setText("Science Average:");

        socialStudiesAverageLabel.setText("Social Studies Average:");

        studentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(studentLabel)
                    .addComponent(readingAverageLabel)
                    .addComponent(mathAverageLabel)
                    .addComponent(scienceAverageLabel)
                    .addComponent(socialStudiesAverageLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(submitButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(readingAverageTextField)
                        .addComponent(mathAverageTextField)
                        .addComponent(scienceAverageTextField)
                        .addComponent(socialStudiesAverageTextField)
                        .addComponent(studentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentLabel)
                    .addComponent(studentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(readingAverageLabel)
                    .addComponent(readingAverageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mathAverageLabel)
                    .addComponent(mathAverageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scienceAverageLabel)
                    .addComponent(scienceAverageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(socialStudiesAverageLabel)
                    .addComponent(socialStudiesAverageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        int result = 0;
        int index = getSelectedComboBoxIndex();
        int studentID = getStudentID(index - 1);
        //insert student grades averages into database
        try(Connection connection = DriverManager.getConnection(URL, username, password)){
            submitGradesStatement = connection.prepareStatement(submitGrades);
            submitGradesStatement.setInt(1, studentID);
            submitGradesStatement.setDouble(2, Double.parseDouble(readingAverageTextField.getText()));
            submitGradesStatement.setDouble(3, Double.parseDouble(mathAverageTextField.getText()));
            submitGradesStatement.setDouble(4, Double.parseDouble(scienceAverageTextField.getText()));
            submitGradesStatement.setDouble(5, Double.parseDouble(socialStudiesAverageTextField.getText()));
            int option = JOptionPane.showConfirmDialog(null, "Are you sure", "Add Grades", JOptionPane.YES_NO_OPTION);
            if (option == 0){
                result = submitGradesStatement.executeUpdate();
                if(result > 0){
                    JOptionPane.showMessageDialog(null, "Grades submitted", "Grades", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                }
            }
        }
        catch(SQLException e){
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_submitButtonActionPerformed
    /**
     * This method sets the values in the combobox
     */
    private void setComboBox(){
        getAllStudents().forEach((student) -> {
            studentComboBox.addItem(student.getFirstName() +" " + student.getLastName());
        });
    }
    /**
     * This method returns the value of the combobox index selected
     * @return 
     */
    private int getSelectedComboBoxIndex(){
        int index = studentComboBox.getSelectedIndex();
        return index;
    }
    /**
     * This method obtains all student ID's from the database
     * This is used to submit grades to the appropriate student.
     * @param index
     * @return 
     */
    private int getStudentID(int index){
        List<Integer> list = new ArrayList<>();
        int studentID = 0;
        try(Connection connection = DriverManager.getConnection(URL, username, password)){
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT studentID FROM students");
            while (resultSet.next())
                list.add(resultSet.getInt("studentID"));
            
            studentID = list.get(index);
        }
        catch(SQLException e){
            System.err.println(e.getMessage());
        }
        return studentID;
    }
    List<Student> getAllStudents(){
        List<Student> studentList = new ArrayList<>();
        try(Connection connection = DriverManager.getConnection(URL, username, password)){
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * FROM students");
            while (resultSet.next()){
                studentList.add(new Student(resultSet.getString("studentID"),
                resultSet.getString("studentFirstName"), resultSet.getString("studentLastName"),
                resultSet.getString("studentAge"), resultSet.getString("studentBirthDate"),
                resultSet.getString("studentAddress"), resultSet.getString("studentCity"),
                resultSet.getString("studentState"), resultSet.getString("studentZip"),
                resultSet.getString("studentPhoneNumber"), resultSet.getString("studentGrade"),
                resultSet.getString("ethnicity"), resultSet.getString("gender")));   
            }
        }
        catch(SQLException e){
            System.err.println(e.getMessage());
        }
        return studentList;
    }
    
    /**
     * This method set the visibility, size, and location of JFrame
     */
    private void setFrame(){
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel mathAverageLabel;
    private javax.swing.JTextField mathAverageTextField;
    private javax.swing.JLabel readingAverageLabel;
    private javax.swing.JTextField readingAverageTextField;
    private javax.swing.JLabel scienceAverageLabel;
    private javax.swing.JTextField scienceAverageTextField;
    private javax.swing.JLabel socialStudiesAverageLabel;
    private javax.swing.JTextField socialStudiesAverageTextField;
    private javax.swing.JComboBox<String> studentComboBox;
    private javax.swing.JLabel studentLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
