
package studinfomgmtsys;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JFrame;

/**
 * The purpose of this class is to add school to the database
 * @author Ralph Julsaint
 */
public class AddSchoolWindow extends javax.swing.JFrame {
    //instance variables
    private final String URL = "jdbc:derby://localhost:1527/schoolDB;create=false";
    private final String username = "julsaint";
    private final String password = "julsaint";
    private final String addSchool = "INSERT INTO school (schoolName, schoolPrincipal, schoolGradeLevel, schoolType, schoolDistrict, schoolAddress, schoolCity, schoolState, schoolZip, schoolPhoneNumber, schoolEmail) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
    private PreparedStatement addSchoolStatement;
    private School school = new School();
    /**
     * Creates new form AddSchoolWindow
     */
    public AddSchoolWindow() {
        super("Register School");
        initComponents();
        setFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        schoolNameLabel = new javax.swing.JLabel();
        schoolPrincipalLabel = new javax.swing.JLabel();
        schoolGradeLevelLabel = new javax.swing.JLabel();
        schoolTypeLabel = new javax.swing.JLabel();
        schoolDistrictLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        zipLabel = new javax.swing.JLabel();
        stateLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        schoolNameTextField = new javax.swing.JTextField();
        schoolPrincipalTextField = new javax.swing.JTextField();
        schoolDistrictTextField = new javax.swing.JTextField();
        schoolTypeComboBox = new javax.swing.JComboBox<>();
        addressTextField = new javax.swing.JTextField();
        cityTextField = new javax.swing.JTextField();
        stateTextField = new javax.swing.JTextField();
        zipTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        schoolGradeLevelComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText(" BusyBee School Manager");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Register your school:");

        schoolNameLabel.setText("School Name:");

        schoolPrincipalLabel.setText("School Principal:");

        schoolGradeLevelLabel.setText("School Grade Level:");

        schoolTypeLabel.setText("School Type:");

        schoolDistrictLabel.setText("School District:");

        cityLabel.setText("City:");

        zipLabel.setText("Zip:");

        stateLabel.setText("State:");

        phoneLabel.setText("Phone:");

        emailLabel.setText("Email:");

        addressLabel.setText("Address:");

        schoolTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Public", "Private", "Other" }));

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        schoolGradeLevelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Elementary", "Middle", "High l" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(205, 205, 205))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(addressLabel)
                                            .addComponent(schoolDistrictLabel)
                                            .addComponent(schoolTypeLabel)
                                            .addComponent(schoolGradeLevelLabel)
                                            .addComponent(schoolPrincipalLabel)
                                            .addComponent(schoolNameLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(schoolNameTextField)
                                            .addComponent(schoolPrincipalTextField)
                                            .addComponent(schoolTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(schoolDistrictTextField)
                                            .addComponent(addressTextField)
                                            .addComponent(schoolGradeLevelComboBox, 0, 170, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(26, 26, 26)
                                                    .addComponent(phoneLabel))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(stateLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(cityLabel, javax.swing.GroupLayout.Alignment.TRAILING))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(zipLabel))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel2)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cityTextField)
                            .addComponent(stateTextField)
                            .addComponent(zipTextField)
                            .addComponent(phoneTextField)
                            .addComponent(emailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schoolNameLabel)
                    .addComponent(schoolNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityLabel)
                    .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schoolPrincipalLabel)
                    .addComponent(schoolPrincipalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateLabel)
                    .addComponent(stateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schoolGradeLevelLabel)
                    .addComponent(zipLabel)
                    .addComponent(zipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(schoolGradeLevelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schoolTypeLabel)
                    .addComponent(schoolTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLabel)
                    .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schoolDistrictLabel)
                    .addComponent(schoolDistrictTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressLabel)
                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * This method submits school data to database
     * @param evt 
     */
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        int result = 0;
        try(Connection connection = DriverManager.getConnection(URL, username, password)){
            String schoolType = schoolTypeComboBox.getSelectedItem().toString();
            String schoolGradeLevel = schoolGradeLevelComboBox.getSelectedItem().toString();
            addSchoolStatement = connection.prepareStatement(addSchool);  
            addSchoolStatement.setString(1, schoolNameTextField.getText());
            addSchoolStatement.setString(2, schoolPrincipalTextField.getText());
            addSchoolStatement.setString(3, schoolGradeLevel);
            addSchoolStatement.setString(4, schoolType);
            addSchoolStatement.setString(5, schoolDistrictTextField.getText());
            addSchoolStatement.setString(6, addressTextField.getText());
            addSchoolStatement.setString(7, cityTextField.getText());
            addSchoolStatement.setString(8, stateTextField.getText());
            addSchoolStatement.setString(9, zipTextField.getText());
            addSchoolStatement.setString(10, phoneTextField.getText());
            addSchoolStatement.setString(11, emailTextField.getText());
            int option = JOptionPane.showConfirmDialog(null, "Are you sure?", "Add School", JOptionPane.YES_NO_OPTION);
            if (option == 0){
                result = addSchoolStatement.executeUpdate();
                if (result > 0){
                    JOptionPane.showMessageDialog(null, "New school added", "New School", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    BusyBeeMainApplicationWindow mainWindow = new BusyBeeMainApplicationWindow();//opens main application window after successful submission
                }
            }
        }
        catch(SQLException e){
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_submitButtonActionPerformed
    /**
     * This method sets the size, location, and visibility of JFrame
     */
    private void setFrame(){
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JLabel schoolDistrictLabel;
    private javax.swing.JTextField schoolDistrictTextField;
    private javax.swing.JComboBox<String> schoolGradeLevelComboBox;
    private javax.swing.JLabel schoolGradeLevelLabel;
    private javax.swing.JLabel schoolNameLabel;
    private javax.swing.JTextField schoolNameTextField;
    private javax.swing.JLabel schoolPrincipalLabel;
    private javax.swing.JTextField schoolPrincipalTextField;
    private javax.swing.JComboBox<String> schoolTypeComboBox;
    private javax.swing.JLabel schoolTypeLabel;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField stateTextField;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel zipLabel;
    private javax.swing.JTextField zipTextField;
    // End of variables declaration//GEN-END:variables
}
