
package com.elimullc.busybee;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
/**
 * The purpose of this class provides the ability to add todo list tasks into database
 * @author Ralph Julsaint
 */
public class AddNewTaskWindow extends javax.swing.JFrame {
    /**
     * Creates new form AddNewTaskWindow
     */
    public AddNewTaskWindow() {
        super("Add Task");
        initComponents();
        setFrame();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel taskLabel = new javax.swing.JLabel();
        taskTextField = new javax.swing.JTextField();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        javax.swing.JLabel dateLabel = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        javax.swing.JLabel timeLabel = new javax.swing.JLabel();
        timeTextField = new javax.swing.JTextField();
        javax.swing.JButton submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        taskLabel.setText("Task:");

        dateLabel.setText("Date:");

        dateTextField.setText("mm/dd/yyyy");

        timeLabel.setText("Time:");

        timeTextField.setText("hh:mm pm");

        submitButton.setText("Submit");
        submitButton.addActionListener(this::submitButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(submitButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taskLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(timeLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(taskTextField)
                            .addComponent(dateTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(timeTextField))))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taskTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taskLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeLabel)
                    .addComponent(timeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * This method submits a new task
     */
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        //submits tasks to database
        int result;
        //instance variables
        String URL = "jdbc:derby:schoolDB;create=false";
        String username = "julsaint";
        String password = "julsaint";
        try(Connection connection = DriverManager.getConnection(URL, username, password)){
            String addTask = "INSERT INTO tasks (taskName, taskDate, taskTime) VALUES (?, ?, ?)";
            PreparedStatement addTaskStatement = connection.prepareStatement(addTask);
            addTaskStatement.setString(1, taskTextField.getText());
            addTaskStatement.setString(2, dateTextField.getText());
            addTaskStatement.setString(3, timeTextField.getText());
            int option = JOptionPane.showConfirmDialog(null, "Are you sure?", "Add Task", JOptionPane.YES_NO_OPTION);
            if (option == 0){
                result = addTaskStatement.executeUpdate();
                if (result > 0){
                    Date date = new Date();
                    Date taskDate = date.dateFromString(dateTextField.getText());
                    ToDo task = new ToDo(taskTextField.getText(), taskDate, timeTextField.getText());
                    JOptionPane.showMessageDialog(null, "Task added");
                    BusyBeeMainApplicationWindow.getToDoListTextArea().append(task.toString());
                    this.dispose();
                }
            }
        }
        catch(SQLException e){
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_submitButtonActionPerformed
    /**
     * This method sets the location size, visible, close operation
     */
    private void setFrame(){
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    private javax.swing.JTextField dateTextField;
    private javax.swing.JTextField taskTextField;
    private javax.swing.JTextField timeTextField;
    // End of variables declaration//GEN-END:variables
}
