
package com.elimullc.busybee;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Objects;
import javax.swing.*;

/**
 * The purpose of this class is to add school to the database
 * @author Ralph Julsaint
 */
public class AddSchoolWindow extends JFrame {
    /**
     * Creates new form AddSchoolWindow
     */
    public AddSchoolWindow() {
        super("Register School");
        initComponents();
        setFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel jLabel1 = new JLabel();
        JLabel jLabel2 = new JLabel();
        JLabel schoolNameLabel = new JLabel();
        JLabel schoolPrincipalLabel = new JLabel();
        JLabel schoolGradeLevelLabel = new JLabel();
        JLabel schoolTypeLabel = new JLabel();
        JLabel schoolDistrictLabel = new JLabel();
        JLabel cityLabel = new JLabel();
        JLabel zipLabel = new JLabel();
        JLabel stateLabel = new JLabel();
        JLabel phoneLabel = new JLabel();
        JLabel emailLabel = new JLabel();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        JLabel addressLabel = new JLabel();
        schoolNameTextField = new JTextField();
        schoolPrincipalTextField = new JTextField();
        schoolDistrictTextField = new JTextField();
        schoolTypeComboBox = new JComboBox<>();
        addressTextField = new JTextField();
        cityTextField = new JTextField();
        stateTextField = new JTextField();
        zipTextField = new JTextField();
        phoneTextField = new JTextField();
        emailTextField = new JTextField();
        JButton submitButton = new JButton();
        schoolGradeLevelComboBox = new JComboBox<>();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new Font("Ubuntu", Font.BOLD, 18)); // NOI18N
        jLabel1.setText(" BusyBee School Manager");

        jLabel2.setFont(new Font("Ubuntu", Font.BOLD, 15)); // NOI18N
        jLabel2.setText("Register your school:");

        schoolNameLabel.setText("School Name:");

        schoolPrincipalLabel.setText("School Principal:");

        schoolGradeLevelLabel.setText("School Grade Level:");

        schoolTypeLabel.setText("School Type:");

        schoolDistrictLabel.setText("School District:");

        cityLabel.setText("City:");

        zipLabel.setText("Zip:");

        stateLabel.setText("State:");

        phoneLabel.setText("Phone:");

        emailLabel.setText("Email:");

        addressLabel.setText("Address:");

        schoolTypeComboBox.setModel(new DefaultComboBoxModel<>(new String[] { "Select", "Public", "Private", "Other" }));

        submitButton.setText("Submit");
        submitButton.addActionListener(this::submitButtonActionPerformed);

        schoolGradeLevelComboBox.setModel(new DefaultComboBoxModel<>(new String[] { "Select", "Elementary", "Middle", "High l" }));

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(205, 205, 205))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(emailLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                            .addComponent(addressLabel)
                                            .addComponent(schoolDistrictLabel)
                                            .addComponent(schoolTypeLabel)
                                            .addComponent(schoolGradeLevelLabel)
                                            .addComponent(schoolPrincipalLabel)
                                            .addComponent(schoolNameLabel))
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                            .addComponent(schoolNameTextField)
                                            .addComponent(schoolPrincipalTextField)
                                            .addComponent(schoolTypeComboBox, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(schoolDistrictTextField)
                                            .addComponent(addressTextField)
                                            .addComponent(schoolGradeLevelComboBox, 0, 170, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addGroup(GroupLayout.Alignment.TRAILING, layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(26, 26, 26)
                                                    .addComponent(phoneLabel))
                                                .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(stateLabel, GroupLayout.Alignment.TRAILING)
                                                        .addComponent(cityLabel, GroupLayout.Alignment.TRAILING))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(zipLabel))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel2)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(cityTextField)
                            .addComponent(stateTextField)
                            .addComponent(zipTextField)
                            .addComponent(phoneTextField)
                            .addComponent(emailTextField, GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(schoolNameLabel)
                    .addComponent(schoolNameTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityLabel)
                    .addComponent(cityTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(schoolPrincipalLabel)
                    .addComponent(schoolPrincipalTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateLabel)
                    .addComponent(stateTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(schoolGradeLevelLabel)
                    .addComponent(zipLabel)
                    .addComponent(zipTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(schoolGradeLevelComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(schoolTypeLabel)
                    .addComponent(schoolTypeComboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLabel)
                    .addComponent(phoneTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(schoolDistrictLabel)
                    .addComponent(schoolDistrictTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel)
                    .addComponent(emailTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(addressLabel)
                    .addComponent(addressTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method submits school data to database
     */
    private void submitButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        int result;
        //instance variables
        String URL = "jdbc:derby:schoolDB;create=false";
        String username = "julsaint";
        String password = "julsaint";
        try(Connection connection = DriverManager.getConnection(URL, username, password)){
            String schoolType = Objects.requireNonNull(schoolTypeComboBox.getSelectedItem()).toString();
            String schoolGradeLevel = Objects.requireNonNull(schoolGradeLevelComboBox.getSelectedItem()).toString();
            String addSchool = "INSERT INTO school (schoolName, schoolPrincipal, schoolGradeLevel, schoolType, schoolDistrict, schoolAddress, schoolCity, schoolState, schoolZip, schoolPhoneNumber, schoolEmail) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement addSchoolStatement = connection.prepareStatement(addSchool);
            addSchoolStatement.setString(1, schoolNameTextField.getText());
            addSchoolStatement.setString(2, schoolPrincipalTextField.getText());
            addSchoolStatement.setString(3, schoolGradeLevel);
            addSchoolStatement.setString(4, schoolType);
            addSchoolStatement.setString(5, schoolDistrictTextField.getText());
            addSchoolStatement.setString(6, addressTextField.getText());
            addSchoolStatement.setString(7, cityTextField.getText());
            addSchoolStatement.setString(8, stateTextField.getText());
            addSchoolStatement.setString(9, zipTextField.getText());
            addSchoolStatement.setString(10, phoneTextField.getText());
            addSchoolStatement.setString(11, emailTextField.getText());
            int option = JOptionPane.showConfirmDialog(null, "Are you sure?", "Add School", JOptionPane.YES_NO_OPTION);
            if (option == 0){
                result = addSchoolStatement.executeUpdate();
                if (result > 0){
                    JOptionPane.showMessageDialog(null, "New school added", "New School", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    new BusyBeeMainApplicationWindow();//opens main application window after successful submission
                }
            }
        }
        catch(SQLException e){
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_submitButtonActionPerformed
    /**
     * This method sets the size, location, and visibility of JFrame
     */
    private void setFrame(){
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    private JTextField addressTextField;
    private JTextField cityTextField;
    private JTextField emailTextField;
    private JTextField phoneTextField;
    private JTextField schoolDistrictTextField;
    private JComboBox<String> schoolGradeLevelComboBox;
    private JTextField schoolNameTextField;
    private JTextField schoolPrincipalTextField;
    private JComboBox<String> schoolTypeComboBox;
    private JTextField stateTextField;
    private JTextField zipTextField;
    // End of variables declaration//GEN-END:variables
}
