
package com.elimullc.busybee;

import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.*;

/**
 * The purpose of this class is to allow student submissions to database
 * @author Ralph Julsaint
 */
public class AddStudentWindow extends JFrame {
    /**
     * Creates new form AddStudentWindow
     */
    public AddStudentWindow() {
        super("New Student");
        initComponents();
        setFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel firstNameLabel = new JLabel();
        firstNameTextField = new JTextField();
        JLabel lastNameLabel = new JLabel();
        lastNameTextField = new JTextField();
        JLabel ageLabel = new JLabel();
        ageTextField = new JTextField();
        JLabel birthDateLabel = new JLabel();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        JLabel addressLabel = new JLabel();
        JLabel cityLabel = new JLabel();
        JLabel stateLabel = new JLabel();
        JLabel zipLabel = new JLabel();
        JLabel phoneNumberLabel = new JLabel();
        JLabel gradeLabel = new JLabel();
        JLabel ethnicityLabel = new JLabel();
        birthDateTextField = new JTextField();
        addressTextField = new JTextField();
        cityTextField = new JTextField();
        stateTextField = new JTextField();
        zipTextField = new JTextField();
        phoneNumberTextField = new JTextField();
        gradeTextField = new JTextField();
        ethnicityTextField = new JTextField();
        JLabel genderLabel = new JLabel();
        genderTextField = new JTextField();
        JButton submitButton = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        firstNameLabel.setText("First Name:");

        lastNameLabel.setText("Last Name:");

        ageLabel.setText("Age:");

        birthDateLabel.setText("Birth Date:");

        addressLabel.setText("Address:");

        cityLabel.setText("City:");

        stateLabel.setText("State:");

        zipLabel.setText("Zip:");

        phoneNumberLabel.setText("Phone Number:");

        gradeLabel.setText("Grade:");

        ethnicityLabel.setText("Ethnicity:");

        genderLabel.setText("Gender:");

        submitButton.setText("Submit");
        submitButton.addActionListener(this::submitButtonActionPerformed);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(submitButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(lastNameLabel)
                            .addComponent(firstNameLabel)
                            .addComponent(ageLabel)
                            .addComponent(birthDateLabel)
                            .addComponent(addressLabel)
                            .addComponent(cityLabel))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ageTextField, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                    .addComponent(lastNameTextField, GroupLayout.Alignment.LEADING)
                                    .addComponent(firstNameTextField, GroupLayout.Alignment.LEADING)
                                    .addComponent(birthDateTextField, GroupLayout.Alignment.LEADING))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(zipLabel, GroupLayout.Alignment.TRAILING)
                                    .addComponent(stateLabel, GroupLayout.Alignment.TRAILING)
                                    .addComponent(phoneNumberLabel, GroupLayout.Alignment.TRAILING)
                                    .addComponent(gradeLabel, GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(addressTextField, GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                    .addComponent(cityTextField))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                    .addComponent(ethnicityLabel)
                                    .addComponent(genderLabel))))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(phoneNumberTextField, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE)
                            .addComponent(gradeTextField, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE)
                            .addComponent(ethnicityTextField, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderTextField, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE)
                            .addComponent(zipTextField, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE)
                            .addComponent(stateTextField, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateLabel)
                    .addComponent(stateTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(zipLabel)
                        .addComponent(zipTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(lastNameLabel)
                        .addComponent(lastNameTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(ageLabel)
                        .addComponent(ageTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(phoneNumberLabel)
                        .addComponent(phoneNumberTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(birthDateLabel)
                    .addComponent(birthDateTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(gradeLabel, GroupLayout.PREFERRED_SIZE, 14, GroupLayout.PREFERRED_SIZE)
                    .addComponent(gradeTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(addressTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(ethnicityLabel)
                    .addComponent(ethnicityTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(cityLabel)
                    .addComponent(cityTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderLabel)
                    .addComponent(genderTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method allows for user to add a new student to database
     */
    private void submitButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        int result;
        //instance variables
        String URL = "jdbc:derby:schoolDB;create=false";
        String username = "julsaint";
        String password = "julsaint";
        try(Connection connection = DriverManager.getConnection(URL, username, password)){
            String addStudent = "INSERT INTO students (studentFirstName, studentLastName, studentAge, studentBirthDate, studentAddress, studentCity, studentState, studentZip, studentPhoneNumber, studentGrade, ethnicity, gender) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement addStudentStatement = connection.prepareStatement(addStudent);
            addStudentStatement.setString(1, firstNameTextField.getText());
            addStudentStatement.setString(2, lastNameTextField.getText());
            addStudentStatement.setString(3, ageTextField.getText());
            addStudentStatement.setString(4, birthDateTextField.getText());
            addStudentStatement.setString(5, addressTextField.getText());
            addStudentStatement.setString(6, cityTextField.getText());
            addStudentStatement.setString(7, stateTextField.getText());
            addStudentStatement.setString(8, zipTextField.getText());
            addStudentStatement.setString(9, phoneNumberTextField.getText());
            addStudentStatement.setString(10, gradeTextField.getText());
            addStudentStatement.setString(11, ethnicityTextField.getText());
            addStudentStatement.setString(12, genderTextField.getText());
            int option = JOptionPane.showConfirmDialog(null, "Are you sure?", "Add Student", JOptionPane.YES_NO_OPTION);
            if (option == 0){
                result = addStudentStatement.executeUpdate();
                if (result > 0){
                    JOptionPane.showMessageDialog(null, "New student added", "New Student", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                }
            }
        }
        catch(SQLException e){
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_submitButtonActionPerformed
    /**
     * This method sets the size, location, and visibility of JFrame
     */
    private void setFrame(){
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    private JTextField addressTextField;
    private JTextField ageTextField;
    private JTextField birthDateTextField;
    private JTextField cityTextField;
    private JTextField ethnicityTextField;
    private JTextField firstNameTextField;
    private JTextField genderTextField;
    private JTextField gradeTextField;
    private JTextField lastNameTextField;
    private JTextField phoneNumberTextField;
    private JTextField stateTextField;
    private JTextField zipTextField;
    // End of variables declaration//GEN-END:variables
}
