
package com.elimullc.busybee;

import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;

/**
 * The purpose of this class is to allow user to log into the application
 * or register as a new user if user does not have an account.
 * @author Ralph Julsaint
 */
public class LoginWindow extends JFrame {
    /**
     * Creates new form LoginWindow
     */
    public LoginWindow() {
        super("Login");
        initComponents();
        setFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel userNameLabel = new JLabel();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        JLabel passwordLabel = new JLabel();
        usernameTextField = new JTextField();
        passwordTextField = new JTextField();
        JButton submitButton = new JButton();
        JButton registerButton = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        userNameLabel.setText("Username:");

        passwordLabel.setText("Password:");

        submitButton.setText("Submit");
        submitButton.addActionListener(this::submitButtonActionPerformed);

        registerButton.setText("Register");
        registerButton.addActionListener(this::registerButtonActionPerformed);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(userNameLabel)
                    .addComponent(passwordLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(registerButton)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(submitButton))
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                        .addComponent(usernameTextField, GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addComponent(passwordTextField)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLabel)
                    .addComponent(usernameTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(registerButton))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This opens a window to add a new user
     */
    private void registerButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AddUserWindow();
    }//GEN-LAST:event_registerButtonActionPerformed

    /**
     * This submits the login information for verification
     */
    private void submitButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        //validates password
        ResultSet resultSet;
        String userPassword = null;
        //instance variables
        String URL = "jdbc:derby:schoolDB;create=false";
        String username = "julsaint";
        String password = "julsaint";
        try(Connection connection = DriverManager.getConnection(URL, username, password)){
            String verifyLogin = "SELECT (password) FROM users WHERE username=?";
            PreparedStatement verifyLoginStatement = connection.prepareStatement(verifyLogin);
            verifyLoginStatement.setString(1, usernameTextField.getText());
            resultSet = verifyLoginStatement.executeQuery();
            while (resultSet.next())
                userPassword = resultSet.getString("password");
            if (userPassword != null && userPassword.equals(passwordTextField.getText())){
                this.dispose();
                new BusyBeeMainApplicationWindow();//if password is validated opens main applicatino window
            }
            else if(!password.equals(passwordTextField.getText())) {
                JOptionPane.showMessageDialog(null, "Wrong username/password");//if password is incorrect
            }
        }
        catch(SQLException | NullPointerException e){
            JOptionPane.showMessageDialog(null, "Login error", "Error", JOptionPane.ERROR_MESSAGE);
            System.err.println(e.getMessage());
            usernameTextField.setText("");
            passwordTextField.setText("");
        }
    }//GEN-LAST:event_submitButtonActionPerformed
    /**
     * This method sets the size, location, and visibility of the JFrame
     */
    private void setFrame(){
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    private JTextField passwordTextField;
    private JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
